# Generated by Django 4.0.6 on 2024-01-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=25)),
                ('data_publicacao', models.DateField()),
                ('fotoCapa', models.ImageField(blank=True, null=True, upload_to='livros_capas/')),
                ('qtd_total', models.PositiveIntegerField(default=0)),
                ('livro_emprestado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='pendente', max_length=20)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo_pessoal.contato')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo_pessoal.livro')),
            ],
        ),
    ]
